DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS contact;

CREATE TABLE user{
  id INTEGER PRIMARY KEY AUTOINCREMENT
  name TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
}


CREATE TABLE contact(
  id INTEGER PRIMARY KEY AUTOINCREMENT
  name TEXT NOT NULL;
  email TEXT NOT NULL,
  message TEXT NOT NULL
);

